app:
  name: "Amartha -  Loan Engine"
  slug_name: "loan-engine"
  version: "1.0.0"
build: 1
mode: "dev"
port: "4000"
db:
  host: "localhost"
  port: "5432"
  name: "loan_engine"
  user: "postgres"
  password: "secret"
  ssl_mode: "disable"
  timezone: "Asia/Jakarta"
  max_idle_conns: 5
  max_open_conns: 20
  conn_max_lifetime: "1h"
  ping_interval: "5000ms"
  retry_attempts: 3
swagger:
  endpoint: "localhost"
  username: "amartha"
  password: "amarthadocs"